title: Welcome to my DevSecOps course Blog
description: This GitHub website is used to demonstation the applicaiton of Jekyll and GitHub Pages. 
show_downloads: true
google_analytics:
about: Ringo
theme: jekyll-theme-architect
